version: '3'
services:
  dev-env:
    build:
      context: .
      args:
        ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - "3000:3000"  # Reactの開発用サーバー
      - "8080:8080"  # Goの開発用サーバー（任意）
      - "2222:22"    # SSH 接続用ポート
    stdin_open: true
    tty: true
    env_file:
      - .env  # .env ファイルをロード
