name: lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.23
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: server # serverをルートディレクトリに指定
          args: ./...               # server内全体を対象にする
      - name: testing
        working-directory: server   # テスト実行時もserverをルートに指定
        run: go test -shuffle on ./...
        continue-on-error: false
